name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run linters and check formatting
        run: |
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
          make fmt vet
